### ISSUE TITLE
Checklist Requerimientos: App Publimetro 2013

### ISSUE THREAD

**Issue by luisespinoza** [desarrollo-altavoz/print2pad#5]
# Flipboard

## Entradas

- [ ] Necesitamos crear un nuevo proyecto Prontus? (sería estimado por EAG, ALD, PRB?)
- [ ] El contenido se gestiona online, no se guarda a menos que el usuario lo indique.
- [ ] El contenido online no se entrega periodicamente, el usuario pide  la actualización.

## Presentación

- [ ] Lista de secciones con preview generadas dinámicamente con contenido online por cada sección.

![listaseccionesconpreviewarticulos](https://f.cloud.github.com/assets/1408903/1004578/51477e72-0aa5-11e3-8ee1-c2fd72e53232.png)

- [ ] Copiar sistema de navegación en secciones. (estilo revista)
- [ ] Dentro de cada sección se redistribuyen (parse) los artículos como si fuera una revista, se usan columnas, pueden exististir varios artículos por página.

![navegacionseccion](https://f.cloud.github.com/assets/1408903/1004595/8f1d7b7a-0aa5-11e3-8a79-a0e3d711fa79.png)

- [ ] Navegación dentro de la sección con los artículos a pantalla completa.
- [ ] Cambio de página con gesto swipe y animación flipboard.

![animacionflipboard](https://f.cloud.github.com/assets/1408903/1004700/d94f304c-0aa7-11e3-934d-a2a8684cdaee.png)

- [ ] Provee búsqueda de artículos
- [ ] Se necesita integración con las redes sociales, si es así, ¿De qué tipo?.

## Seguridad

- [ ] Especificar si se necesita encriptar contenido.
- [ ] Especificar si se necesita control de acceso con solicitud de credenciales.
- [ ] Especificar la formación vital que debe ser protegida de las fallas.

# Adobe 

## Entradas

- [ ] Necesitamos cambiar algo en el formato del contenido que estamos entregando actualmente?

## Presentación
- [ ] Actualizar apariencia del front end según la apariencia estándar de Adobe Digital Publishing System
- [ ] Cambiar previews de la parte inferior por slider.
- [ ] Agregar vista lateral con índice de artículos.

# Ambos

## Calidad de requerimientos

- [ ] Revisar que los requerimientos no se contradigan entre ellos.
- [ ] Revisar que los requerimientos están escritos en el lenguaje del cliente.
- [ ] Revisar que los requerimientos especifican trade-offs aceptables.
- [ ] Revisar que los requerimientos evitan especificar el diseño del software (clases, arquitectura, etc).
- [ ] Revisar que los requerimientos están en un nivel adecuado de detalle, si necesita más o menos detalle, modificar.
- [ ] Revisar que cada requerimiento sea relevante para la formulación del problema y/o para la implementación de la solución.
- [ ] Revisar que los requerimientos sean verificables por el equipo de desarrollo y un equipo independiente.

## Requerimientos completos
- [ ] Se han especificado las áreas que aún no cuentan con información?
- [ ] Revisar que están listados todos los requerimientos, que una vez completos, darán por aceptado el proyecto.
- [ ] Revisar que no existan requerimientos imposibles de cumplir que solo han sido agregados para dar el gusto del cliente o el jefe.
